dataset:
  task: classification
  data_dir: datasets/images-classification
  image_size: 224
  mode: all       # 🔹 현재 학습 목적이면 이거 추가 추천

train:
  batch_size: 32
  shuffle: true
  epochs: 10        # 🔹 최소 반복 횟수 지정 (러너에서 필요할 수 있음)
  lr: 0.001         # 🔹 학습률 (옵션)

model:
  path: models/toy_empty_model.py
  class_name: ToyClassifier
  args:
    num_classes: 5
    hidden_dim: 256

experiment:
  mode: all       # 🔹 러너의 실행 모드 분기 (train, val, predict 등)

output:
  save_dir: runs/classify-test-001   # 🔹 결과 저장 위치