name: model-playground-mac
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - opencv
  - pytorch
  - pip:
      - ultralytics
      - scikit-learn
      - jupyterlab